// Custom hook for session management.

import { useState, useCallback, useEffect } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import type { SessionInfo } from '../types';

interface UseSessionsReturn {
  sessions: SessionInfo[];
  activeSessionId: string | null;
  loading: boolean;
  createSession: (title?: string, options?: { agentId?: string | null }) => Promise<SessionInfo | null>;
  selectSession: (id: string) => void;
  deleteSession: (id: string) => Promise<void>;
  refreshSessions: () => Promise<void>;
  forkSession: (sessionId: string, messageIndex: number, title?: string) => Promise<SessionInfo | null>;
}

// Polling interval in ms -- keeps session titles and new sessions from the TUI in sync.
const SESSION_POLL_INTERVAL_MS = 5_000;

export function useSessions(agentId?: string | null): UseSessionsReturn {
  const [sessions, setSessions] = useState<SessionInfo[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const refreshSessions = useCallback(async () => {
    try {
      const list = await invoke<SessionInfo[]>('session_list', {
        agentId: agentId ?? null,
      });
      setSessions(list);
      setActiveSessionId((current) => (
        current && !list.some((session) => session.id === current) ? null : current
      ));
    } catch (e) {
      console.error('Failed to load sessions:', e);
    } finally {
      setLoading(false);
    }
  }, [agentId]);

  // Initial load.
  useEffect(() => {
    refreshSessions();
  }, [refreshSessions]);

  // Periodic refresh so that titles generated by the backend (or TUI-created
  // sessions) appear without requiring the user to manually reload.
  useEffect(() => {
    const id = setInterval(refreshSessions, SESSION_POLL_INTERVAL_MS);
    return () => clearInterval(id);
  }, [refreshSessions]);

  // Refresh immediately when the window gains focus -- catches sessions
  // created in the TUI while the GUI was in the background.
  useEffect(() => {
    const handleVisibility = () => {
      if (document.visibilityState === 'visible') {
        refreshSessions();
      }
    };
    document.addEventListener('visibilitychange', handleVisibility);
    // Also handle OS-level window focus (e.g. Alt-Tab).
    window.addEventListener('focus', refreshSessions);
    return () => {
      document.removeEventListener('visibilitychange', handleVisibility);
      window.removeEventListener('focus', refreshSessions);
    };
  }, [refreshSessions]);

  // Listen for title updates emitted by the GUI backend after LLM turns.
  useEffect(() => {
    let unlisten: (() => void) | undefined;
    listen<{ session_id: string; title: string }>('session:title_updated', (e) => {
      setSessions((prev) =>
        prev.map((s) =>
          s.id === e.payload.session_id ? { ...s, title: e.payload.title } : s,
        ),
      );
    }).then((fn) => { unlisten = fn; });
    return () => { unlisten?.(); };
  }, []);

  const createSession = useCallback(
    async (title?: string, options?: { agentId?: string | null }): Promise<SessionInfo | null> => {
      try {
        const session = await invoke<SessionInfo>('session_create', {
          title: title ?? null,
          agentId: options?.agentId ?? agentId ?? null,
        });
        setSessions((prev) => [session, ...prev]);
        setActiveSessionId(session.id);
        return session;
      } catch (e) {
        console.error('Failed to create session:', e);
        return null;
      }
    },
    [agentId],
  );

  const selectSession = useCallback((id: string) => {
    setActiveSessionId(id);
  }, []);

  const deleteSession = useCallback(
    async (id: string) => {
      try {
        await invoke('session_delete', { sessionId: id });
        setSessions((prev) => prev.filter((s) => s.id !== id));
        if (activeSessionId === id) {
          setActiveSessionId(null);
        }
      } catch (e) {
        console.error('Failed to delete session:', e);
      }
    },
    [activeSessionId],
  );

  const forkSession = useCallback(
    async (sessionId: string, messageIndex: number, title?: string): Promise<SessionInfo | null> => {
      try {
        const fork = await invoke<SessionInfo>('session_fork', {
          sessionId,
          messageIndex,
          title: title ?? null,
        });
        setSessions((prev) => [fork, ...prev]);
        setActiveSessionId(fork.id);
        return fork;
      } catch (e) {
        console.error('Failed to fork session:', e);
        return null;
      }
    },
    [],
  );

  return {
    sessions,
    activeSessionId,
    loading,
    createSession,
    selectSession,
    deleteSession,
    refreshSessions,
    forkSession,
  };
}
