// Custom hook for session management.

import { useState, useCallback, useEffect } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import type { SessionInfo } from '../types';

interface UseSessionsReturn {
  sessions: SessionInfo[];
  activeSessionId: string | null;
  loading: boolean;
  createSession: (title?: string) => Promise<SessionInfo | null>;
  selectSession: (id: string) => void;
  deleteSession: (id: string) => Promise<void>;
  refreshSessions: () => Promise<void>;
}

// Polling interval in ms -- keeps session titles and new sessions from the TUI in sync.
const SESSION_POLL_INTERVAL_MS = 30_000;

export function useSessions(): UseSessionsReturn {
  const [sessions, setSessions] = useState<SessionInfo[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const refreshSessions = useCallback(async () => {
    try {
      const list = await invoke<SessionInfo[]>('session_list');
      setSessions(list);
    } catch (e) {
      console.error('Failed to load sessions:', e);
    } finally {
      setLoading(false);
    }
  }, []);

  // Initial load.
  useEffect(() => {
    refreshSessions();
  }, [refreshSessions]);

  // Periodic refresh so that titles generated by the backend (or TUI-created
  // sessions) appear without requiring the user to manually reload.
  useEffect(() => {
    const id = setInterval(refreshSessions, SESSION_POLL_INTERVAL_MS);
    return () => clearInterval(id);
  }, [refreshSessions]);

  // Listen for title updates emitted by the GUI backend after LLM turns.
  useEffect(() => {
    let unlisten: (() => void) | undefined;
    listen<{ session_id: string; title: string }>('session:title_updated', (e) => {
      setSessions((prev) =>
        prev.map((s) =>
          s.id === e.payload.session_id ? { ...s, title: e.payload.title } : s,
        ),
      );
    }).then((fn) => { unlisten = fn; });
    return () => { unlisten?.(); };
  }, []);

  const createSession = useCallback(
    async (title?: string): Promise<SessionInfo | null> => {
      try {
        const session = await invoke<SessionInfo>('session_create', {
          title: title ?? null,
        });
        setSessions((prev) => [session, ...prev]);
        setActiveSessionId(session.id);
        return session;
      } catch (e) {
        console.error('Failed to create session:', e);
        return null;
      }
    },
    [],
  );

  const selectSession = useCallback((id: string) => {
    setActiveSessionId(id);
  }, []);

  const deleteSession = useCallback(
    async (id: string) => {
      try {
        await invoke('session_delete', { sessionId: id });
        setSessions((prev) => prev.filter((s) => s.id !== id));
        if (activeSessionId === id) {
          setActiveSessionId(null);
        }
      } catch (e) {
        console.error('Failed to delete session:', e);
      }
    },
    [activeSessionId],
  );

  return {
    sessions,
    activeSessionId,
    loading,
    createSession,
    selectSession,
    deleteSession,
    refreshSessions,
  };
}
