#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WRAPPER_TEMPLATE="$REPO_ROOT/packaging/linux/appimage/AppRun"

SOURCE_APPIMAGE=""
OUTPUT_DIR=""
OUTPUT_NAME=""
APPIMAGETOOL_BIN="${APPIMAGETOOL:-}"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/package-linux-appimage.sh \
    --source-appimage /path/to/original.AppImage \
    --output-dir /path/to/output

Options:
  --source-appimage PATH   Existing AppImage generated by Tauri.
  --output-dir DIR         Directory for the patched AppImage.
  --output-name NAME       Optional output filename override.
  --appimagetool PATH      Path to appimagetool or appimagetool AppImage.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-appimage)
      SOURCE_APPIMAGE="${2:-}"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="${2:-}"
      shift 2
      ;;
    --output-name)
      OUTPUT_NAME="${2:-}"
      shift 2
      ;;
    --appimagetool)
      APPIMAGETOOL_BIN="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument '$1'" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$SOURCE_APPIMAGE" || -z "$OUTPUT_DIR" ]]; then
  echo "error: --source-appimage and --output-dir are required" >&2
  usage >&2
  exit 1
fi

if [[ "$SOURCE_APPIMAGE" != /* ]]; then
  SOURCE_APPIMAGE="$PWD/$SOURCE_APPIMAGE"
fi

if [[ ! -f "$SOURCE_APPIMAGE" ]]; then
  echo "error: AppImage not found: $SOURCE_APPIMAGE" >&2
  exit 1
fi

if [[ ! -f "$WRAPPER_TEMPLATE" ]]; then
  echo "error: AppRun wrapper template not found: $WRAPPER_TEMPLATE" >&2
  exit 1
fi

if [[ -z "$APPIMAGETOOL_BIN" ]]; then
  if command -v appimagetool >/dev/null 2>&1; then
    APPIMAGETOOL_BIN="$(command -v appimagetool)"
  else
    echo "error: appimagetool not found; pass --appimagetool or set APPIMAGETOOL" >&2
    exit 1
  fi
fi

mkdir -p "$OUTPUT_DIR"

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) ARCH="x86_64" ;;
  aarch64|arm64) ARCH="aarch64" ;;
esac

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

extract_appimage() {
  local appimage="$1"
  (
    cd "$TMP_DIR"
    "$appimage" --appimage-extract >/dev/null
  )
}

run_appimagetool() {
  local appdir="$1"
  local output="$2"

  if [[ "$APPIMAGETOOL_BIN" == *.AppImage ]]; then
    ARCH="$ARCH" "$APPIMAGETOOL_BIN" --appimage-extract-and-run "$appdir" "$output"
  else
    ARCH="$ARCH" "$APPIMAGETOOL_BIN" "$appdir" "$output"
  fi
}

prune_graphics_stack() {
  local appdir="$1"
  local -a patterns=(
    'libEGL.so*'
    'libGL.so*'
    'libGLESv1_CM.so*'
    'libGLESv2.so*'
    'libgbm.so*'
    'libdrm.so*'
    'libdrm_*.so*'
    'libwayland-egl.so*'
  )

  if [[ "${APPIMAGE_KEEP_BUNDLED_GL:-0}" == "1" ]]; then
    echo "  Keeping bundled GL/EGL stack (APPIMAGE_KEEP_BUNDLED_GL=1)"
    return
  fi

  echo "  Pruning bundled GL/EGL stack from extracted AppDir..."
  for pattern in "${patterns[@]}"; do
    while IFS= read -r -d '' path; do
      echo "    removed $(realpath --relative-to="$appdir" "$path")"
      rm -f "$path"
    done < <(find "$appdir" \( -type f -o -type l \) -name "$pattern" -print0)
  done

  while IFS= read -r -d '' dir; do
    echo "    removed $(realpath --relative-to="$appdir" "$dir")"
    rm -rf "$dir"
  done < <(find "$appdir" -type d \( -name dri -o -path '*/glvnd/*' \) -print0)
}

install_wrapper() {
  local appdir="$1"
  if [[ ! -e "$appdir/AppRun" ]]; then
    echo "error: extracted AppDir does not contain AppRun" >&2
    exit 1
  fi

  mv "$appdir/AppRun" "$appdir/AppRun.origin"
  cp "$WRAPPER_TEMPLATE" "$appdir/AppRun"
  chmod 755 "$appdir/AppRun"
}

extract_appimage "$SOURCE_APPIMAGE"
APPDIR="$TMP_DIR/squashfs-root"

if [[ ! -d "$APPDIR" ]]; then
  echo "error: failed to extract AppImage payload" >&2
  exit 1
fi

install_wrapper "$APPDIR"
prune_graphics_stack "$APPDIR"

if [[ -z "$OUTPUT_NAME" ]]; then
  OUTPUT_NAME="$(basename "$SOURCE_APPIMAGE")"
fi

OUTPUT_PATH="$OUTPUT_DIR/$OUTPUT_NAME"
rm -f "$OUTPUT_PATH"

echo "  Repacking patched AppImage..."
run_appimagetool "$APPDIR" "$OUTPUT_PATH"
chmod 755 "$OUTPUT_PATH"

echo "Patched AppImage written to $OUTPUT_PATH"
